org: moullxndev
service: blog-api

provider:
  name: aws
  runtime: nodejs22.x
  architecture: arm64
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  httpApi:
    cors:
      allowedOrigins:
        - http://localhost:5173
      allowedHeaders:
        - Content-Type
        - Authorization
      allowedMethods:
        - GET
        - POST
        - PATCH
        - DELETE
        - OPTIONS
    authorizers:
      jwtAuthorizer:
        type: jwt
        identitySource: $request.header.Authorization
        issuerUrl: !GetAtt CognitoUserPool.ProviderURL
        audience:
          - !Ref CognitoUserPoolClient

  environment:
    COGNITO_USER_POOL_ID: !Ref CognitoUserPool
    COGNITO_CLIENT_ID: !Ref CognitoUserPoolClient
    TABLE_NAME: blog-${self:provider.stage}
    BUCKET_NAME: !Ref ImagesBucket
  iam:
    role:
      statements:
        - Effect: Allow
          Resource: !Sub "arn:aws:s3:::${ImagesBucket}/*"
          Action:
            - s3:PutObject

        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:Query
            - dynamodb:GetItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - !GetAtt MainTable.Arn
            - !Sub "${MainTable.Arn}/index/*"

package:
  individually: true

custom:
  esbuild:
    bundle: true
    minify: true
    sourcemap: false

functions:
  - ${file(./sls/functions/Auth.yml)}
  - ${file(./sls/functions/Users.yml)}
  - ${file(./sls/functions/Articles.yml)}
  - ${file(./sls/functions/Roles.yml)}
  - ${file(./sls/functions/Images.yml)}

resources:
  - ${file(./sls/resources/UserPool.yml)}
  - ${file(./sls/resources/MainTable.yml)}
  - ${file(./sls/resources/ImagesBucket.yml)}
