Resources:
  ImagesBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: ${self:service}-images-${self:provider.stage}
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders: ["*"]
            AllowedMethods: [GET, PUT, POST]
            AllowedOrigins: ["http://localhost:5173"]
            ExposedHeaders: [ETag]

  ImagesBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ImagesBucket
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal: "*"
            Action: s3:GetObject
            Resource: !Sub "arn:aws:s3:::${ImagesBucket}/*"
