Resources:
  ImagesBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: ${self:service}-images-${self:provider.stage}
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders: ["*"]
            AllowedMethods: [PUT, POST]
            AllowedOrigins: ["http://localhost:5173"]
            ExposedHeaders: [ETag]
