import type { Article } from "./types";

export const MOCK_ARTICLES: Article[] = [
  {
    articleId: "a1b2c3d4-0001",
    title: "Getting Started with TypeScript — um guia para quem sai do JavaScript",
    slug: "getting-started-with-typescript",
    tags: ["typescript", "javascript", "tutorial"],
    visibility: "public",
    createdAt: "2026-04-15T10:00:00Z",
    authorName: "Lucas Bertoncello",
    likeCount: 24,
    commentCount: 5,
  },
  {
    articleId: "a1b2c3d4-0002",
    title: "React 19 e o que mudou de vez — Server Components na prática",
    slug: "react-19-server-components",
    tags: ["react", "frontend"],
    visibility: "students_only",
    createdAt: "2026-04-10T14:30:00Z",
    authorName: "Ana Souza",
    likeCount: 17,
    commentCount: 3,
  },
  {
    articleId: "a1b2c3d4-0003",
    title: "Clean Architecture na prática com Node.js",
    slug: "clean-architecture-nodejs",
    tags: ["arquitetura", "nodejs", "backend"],
    visibility: "public",
    createdAt: "2026-04-02T09:15:00Z",
    authorName: "Pedro Martins",
    likeCount: 41,
    commentCount: 9,
  },
  {
    articleId: "a1b2c3d4-0004",
    title: "DDD na era dos microsserviços — como estruturar domínios de forma sustentável",
    slug: "ddd-microsservicos-dominios",
    tags: ["ddd", "arquitetura"],
    visibility: "students_only",
    createdAt: "2026-03-28T16:00:00Z",
    authorName: "Carlos Ribeiro",
    likeCount: 33,
    commentCount: 7,
  },
  {
    articleId: "a1b2c3d4-0005",
    title: "Entendendo o Event Loop do JavaScript de uma vez por todas",
    slug: "event-loop-javascript",
    tags: ["javascript", "performance"],
    visibility: "public",
    createdAt: "2026-03-20T11:00:00Z",
    authorName: "Mariana Costa",
    likeCount: 58,
    commentCount: 12,
  },
  {
    articleId: "a1b2c3d4-0006",
    title: "Testes de integração que realmente valem a pena escrever",
    slug: "testes-integracao-que-valem",
    tags: ["testes", "qualidade"],
    visibility: "students_only",
    createdAt: "2026-03-14T08:45:00Z",
    authorName: "Rafael Oliveira",
    likeCount: 29,
    commentCount: 4,
  },
  {
    articleId: "a1b2c3d4-0007",
    title: "Zustand vs Redux — quando usar cada um e por quê",
    slug: "zustand-vs-redux",
    tags: ["react", "frontend", "typescript"],
    visibility: "public",
    createdAt: "2026-03-07T13:20:00Z",
    authorName: "Fernanda Lima",
    likeCount: 46,
    commentCount: 15,
  },
  {
    articleId: "a1b2c3d4-0008",
    title: "Monorepos com Turborepo — estrutura e boas práticas para times",
    slug: "monorepos-turborepo",
    tags: ["backend", "arquitetura", "nodejs"],
    visibility: "students_only",
    createdAt: "2026-02-28T10:00:00Z",
    authorName: "Gustavo Alves",
    likeCount: 21,
    commentCount: 6,
  },
];
